### ISSUE TITLE
event xy() does not account for container's position

### ISSUE THREAD

**Issue by arvind** [vega/vega-view#13]
With the following spec, click the same location (e.g., (40, 40) as per the axes) with a normal/default parse output and with a `padding-left: 50px` style added to the container. In the first case, when the container is flush with its parent, a warn of approximately `42` is printed. In the second, the coordinate is offset by the padding (and warns `92`). 

`xy()` should return the coordinates relative to the view coordinate space, which should be agnostic to the positioning of the container element. 

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 200,
  "height": 200,
  "encode": {"enter": {"fill": {"value": "transparent"}}},
  "signals": [
    {
      "name": "brush_x",
      "on": [{"events": "mousedown","update": "warn(x())"}]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "domain": [0,200],
      "range": [0,200]
    },
    {
      "name": "y",
      "type": "linear",
      "domain": [0,200],
      "range": [200,0]
    }
  ],
  "axes": [
    {"scale": "x","orient": "bottom","grid": true},
    {"scale": "y","orient": "left","grid": true}
  ]
}
```

**Comment by jheer** [comment]
Fixed, and released in vega-view v1.2.2.
