### ISSUE TITLE
`tooltipHandler` never fires

### ISSUE THREAD

**Issue by ericsoco** [vega/vega-view#16]
I've initialized a `tooltipHandler` like so:

```
view.tooltipHandler((event, item, text) => {
  console.log({text});
});
```

Stepping through Vega source in a debugger, I see that the handler is assigned correctly in `View.tooltipHandler`.

However, SVGHandler's `_handleTooltip` function is never called because the `item` passed into `_tooltipHandler` never has a `.tooltip` property (presumably supposed to be assigned by the scenegraph?).

I called `view.hover()` before `view.tooltipHandler()` so event handlers should be getting registered (and in fact, I think `SVGHandler._tooltipHandler()` would not be called otherwise). Is there something else I'm missing to leverage this functionality?

**Comment by jheer** [comment]
The tooltip handler is specifically designed to respond to interactions with scenegraph items that have a `tooltip` property (typically containing the tooltip text). By design, the handler does not fire if the `tooltip` property is null or undefined. Custom handlers can be added to change either (a) how the `tooltip` property data is processed or (b) how the tooltip is presented in the UI.

If you'd like to apply a more general handler (regardless of the `tooltip` property value) you can instead register more general event listeners.

**Comment by ericsoco** [comment]
Ok, that jibes with what I see in the code. I guess the remaining question, then, is:

How is the `tooltip` property set on a scenegraph item? Is this something that can be defined in a `mark` spec? Is there more documentation somewhere that describes the intended usage of the scenegraph `tooltip` property and `View.tooltipHandler()` API? (Given that the latter doesn't work without correctly setting up the former.)

If there's not documentation of the scenegraph `tooltip` property yet, a link to relevant source would help instead. Not finding anything within `vega-scenegraph` that sets `item.tooltip`. Thanks Jeff!

**Comment by jheer** [comment]
Yes, you can define `tooltip` using a standard mark encoding channel (just like `x`, `y`, `fill`, etc). Often you might use a signal expression to generate your desired tooltip text string. It is included in the documentation pages for each individual mark type, e.g., https://vega.github.io/vega/docs/marks/arc/

The default expectation is for `tooltip` to be a string (or string coercible) value, which is then displayed using the browser's built-in tooltip support via the HTML document element `title` attribute. However, as noted above, custom tooltip handlers can be used to change how the value of the `tooltip` property is interpreted and/or presented.
