### ISSUE TITLE
Enable custom "range" bind labels

### ISSUE THREAD

**Issue by janpipek** [vega/vega-view#19]
Hello.

When a signal is bound to a range input control, the label beneath the slider is set to reflect the "value" of the "input". This value must be numeric.

However, I would very much appreciate to be able to set a label with customized text (concretely, some additional info about the value selected - e.g. element of the array where item descriptions are stored). Could it be possible to pass either a list of values to select from or a mapping function when creating the binding?

Thanks for considering this idea,
Jan

**Comment by jheer** [comment]
Thanks for the suggestion! However, I don't think we will be adding this feature any time soon. I could imagine potentially adding a new property to bindings that includes a signal expression for the label string, but this would also add more complexity for a rarely needed feature that can be achieved by other means (albeit not solely within a Vega JSON spec).

In addition to Vega's built-in binding support, you can create bindings externally using the Vega View API. For example, you could instantiate your own HTML input elements. When those input elements are modified, an event handler could set the appropriate signal values on the View. For the other direction of the binding, you can add signal listeners to the View and update the input element in response. If you do this, you then have full control over the input elements and any corresponding labels.

**Comment by janpipek** [comment]
Hi, I understand that this is a marginal feature. Unfortunately, scripting from outside (even if I learn how to access the appropriate layers) does not exactly solve my problem, as I want to create a full JSON specification in a Python script and pass it as data to whoever wants to render it :-(

I'll try to deal with it.
Thanks.
