### ISSUE TITLE
Access/List all datasets

### ISSUE THREAD

**Issue by domoritz** [vega/vega-view#21]
In previous versions of Vega, we could run `view.data()` but `data` now requires the name of a dataset. Is there an official way to list all datasets (without going into `_runtime`)?

cc @ydlamba

**Comment by jheer** [comment]
How about this?

```js
view.getState({data: vega.truthy, signals: vega.falsy, recurse: true});
```

**Comment by domoritz** [comment]
Works in the editor with `VEGA_DEBUG.view.getState({data: VEGA_DEBUG.vega.truthy, signals: VEGA_DEBUG.vega.falsy, recurse: true});`. 🎉
