### ISSUE TITLE
View component does not resize hconcat charts

### ISSUE THREAD

**Issue by d-werner** [vega/vega-view#22]
Hi everybody!

I'm using view component's [width function](https://github.com/vega/vega-view#view_width) to make the width of `vconcat` charts reactive to the width of its parent or container node. 
When I tried the same with `hconcat`charts I expected the contained charts to be evenly distributed over the given width. But although the canvas gets resized, the charts themselves are not affected.

Passing the width option to the vega embed function does not work either.

The behaviour is reproducible in the [vega editor](https://vega.github.io/editor) using this spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "url": "data/cars.json"
  },
  "hconcat": [
    {
      "mark": "line",
      "encoding": {
        "x": {
          "field": "Year",
          "type": "temporal"
        },
        "y": {
          "aggregate": "mean",
          "field": "Miles_per_Gallon",
          "type": "quantitative"
        },
        "shape": {
          "field": "Origin",
          "type": "nominal",
          "legend": null
        },
        "color": {
          "field": "Origin",
          "type": "nominal",
          "legend": null
        }
      }
    },
    {
      "mark": "line",
      "encoding": {
        "x": {
          "field": "Year",
          "type": "temporal"
        },
        "y": {
          "aggregate": "mean",
          "field": "Miles_per_Gallon",
          "type": "quantitative"
        },
        "shape": {
          "field": "Origin",
          "type": "nominal",
          "legend": null
        },
        "color": {
          "field": "Origin",
          "type": "nominal",
          "legend": null
        }
      }
    }
  ]
}
```

This is how it looks initially:
<img width="1369" alt="bildschirmfoto 2018-05-25 um 19 34 21" src="https://user-images.githubusercontent.com/2510850/40559828-54718cec-6058-11e8-862b-9ace2bc57849.png">

And when you run `VEGA_DEBUG.view.width(800).run()` in the developer console, only the white canvas expands to the right.

<img width="1334" alt="bildschirmfoto 2018-05-25 um 19 34 50" src="https://user-images.githubusercontent.com/2510850/40559793-331ed1da-6058-11e8-9eda-3ddd125e9190.png">

**Comment by domoritz** [comment]
If you look at the Vega spec that is being generated, you can see that there are signals for the width of the individual views. You need to adjust those:

```
VEGA_DEBUG.view.signal('concat_0_width', 100).run()
```

**Comment by d-werner** [comment]
Great! That solves the problem for me. 
Thx for your swift help! 

As far as I'm concerned, this issue is resolved. 
But I leave it to you to close the issue, because I don't know what you think of the user expectation of an automatic resize of the individual views.

**Comment by domoritz** [comment]
We would love to be able to resize composed charts with just setting the width but it requires a few fundamental changes in Vega and Vega-Lite.
