### ISSUE TITLE
"loadOptions" is not supported on View constructor

### ISSUE THREAD

**Issue by rgrzywinski** [vega/vega-view#3]
The main `vega-view` readme references `loadOptions` but it does not appear to be supported. (Only `loader`, `logLevel`, `renderer` and `functions` are supported -- of which the first and last are not documented as such.)

**Comment by jheer** [comment]
Thanks! The documentation was out of date, and has been fixed to reflect the `loader` option. The `functions` option is indeed supported, but is intentionally undocumented as it is not part of the standard "public" API.
