### ISSUE TITLE
Support setting a loader when creating a View

### ISSUE THREAD

**Issue by rgrzywinski** [vega/vega-view#4]
The following code is desirable:

```JavaScript
var loader = vega.loader({mode: 'http', baseURL: 'https://blah.example.com'});
var view = new vega.View(runtime)
	.loader(loader) // SET A LOADER
	.logLevel(vega.Warn)
	.initialize(document.querySelector('#vis'))
	.renderer('canvas')
	.hover()
	.run();
```

But does not work. The following is the only option:

```JavaScript
var loader = vega.loader({mode: 'http', baseURL: 'https://blah.example.com'});
var view = new vega.View(runtime, {loader: loader})
	.logLevel(vega.Warn)
	.initialize(document.querySelector('#vis'))
	.renderer('canvas')
	.hover()
	.run();
```

Given that `DataFlow` supports the `loader()` method I would expect `View` to also support it.

(VL: v2.0.0-alpha.6; VG: v3.0.0-beta.27)

**Comment by jheer** [comment]
Thanks! The View component does have a `loader` method, initially inherited from Dataflow (which is the superclass of View). I've now updated the `loader` method for the View class to support changing the loader _after_ view initialization, and added documentation.
